<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "aimeos_dist"
 *
 * Auto generated by Extension Builder 2015-01-02
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Aimeos web shop distribution',
	'description' => 'Professional, full-featured and ultra-fast TYPO3 e-commerce distribution for online shops, complex B2B applications and #gigacommerce. Turns TYPO3 into the best platform for content commerce and your e-commerce requirements',
	'category' => 'distribution',
	'author' => 'Aimeos',
	'author_email' => 'aimeos@aimeos.org',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '21.7.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '10.4.0-10.99.99',
			'bootstrap_package' => '11.0.0-11.99.99',
			'aimeos' => '21.7.0-21.10.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
