<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "aimeos_dist"
 *
 * Auto generated by Extension Builder 2015-01-02
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Aimeos web shop distribution',
	'description' => 'Aimeos web shop distribution',
	'category' => 'distribution',
	'author' => 'Aimeos',
	'author_email' => 'aimeos@aimeos.org',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-7.0.99',
			'aimeos' => '2.0.0-2.99.99',
			'bootstrap_package' => '6.2.0-6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
			'realurl' => '1.12.8-1.99.99'
		),
	),
);