<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "aimeos_dist"
 *
 * Auto generated by Extension Builder 2015-01-02
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Aimeos web shop distribution',
	'description' => 'The Aimeos web shop distribution is a fast, flexible and usability optimized shop system and e-commerce solution available in multiple languages. It contains all necessary components for running a web shop and integrates perfectly in CRM and ERP systems as well as payment and delivery service providers',
	'category' => 'distribution',
	'author' => 'Aimeos',
	'author_email' => 'aimeos@aimeos.org',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '17.10.2',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-8.99.99',
			'bootstrap_package' => '7.1.0-8.99.99',
			'aimeos' => '18.4.0-18.99.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
			'realurl' => '1.13.7-2.99.99',
		),
	),
);
