services:
  Aimeos\AimeosDist\EventListener\Setup:
    tags:
      - name: event.listener
        identifier: 'aimeos.setup'
        event: TYPO3\CMS\Extensionmanager\Event\AfterExtensionDatabaseContentHasBeenImportedEvent
        before: ''